wandeldigital:
    hostname: wandeldigital.de
    stage: staging
    branch: master
    deploy_path: ~/zahnarzt.wandeldigital.de
    bin/composer: composer
    # bin/npm: npm
    bin/wp: wp
    sites:
        the-theme.main: zahnarzt.wandeldigital.de
