production:
    hostname: dr-ladwig.com
    stage: production
    branch: master
    deploy_path: ~/website_2020
    bin/composer: /usr/bin/php7.3-cli ~/composer.phar
    # bin/npm: npm
    bin/wp: /usr/bin/php7.3-cli ~/wp-cli.phar
    sites:
        johannes-ladwig.main: dr-ladwig.com

staging:
    hostname: justusdeitert.de
    stage: staging
    branch: development
    deploy_path: ~/dr-ladwig.justusdeitert.de
    bin/composer: composer
    # bin/npm: npm
    bin/wp: wp
    sites:
        johannes-ladwig.main: dr-ladwig.justusdeitert.de
