wandeldigital:
    hostname: wandeldigital.de
    stage: staging
    branch: master
    deploy_path: ~/zahnarzt.wandeldigital.de
    bin/composer: /opt/plesk/php/7.4/bin/php ~/composer.phar
    # bin/npm: npm
    bin/wp: /opt/plesk/php/7.4/bin/php ~/wp-cli.phar
    sites:
        the-theme.main: zahnarzt.wandeldigital.de
